### ISSUE TITLE
Integrating Stimpack with ShieldBattery

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/stimpack#2]
Currently the Stimpack repo contains the code which implements a newer injection method (in Rust!) than what we're currently using in SB. Using this method should give us two fairly big benefits in SB:

- Wine support (we hope?); which in turn gets all the Linux nerds off our backs. Just kidding, we love you. All 3 of you.
- Excising the last remnants of the C++ code, and more importantly its build pipeline, from our codebase and workflow. Hooray!

However, to get this repository to a point where it can be used by SB there's still some work left, and by my understanding that involves the following:

- Integrate the injection code with neon so it can be used in SB as a node.js native addon.
- Make the code async so the javascript code in SB doesn't block while waiting for injection to finish.
- Propagate all of the errors correctly so they can be handled in the application.

This issue can serve as a place to discuss the remaining work in detail, and let any brave souls who might take on this task to ask any questions they might have. Good luck!

**Comment by arilou** [comment]
Sounds good @2Pacalypse- , I see today the API for neon is separated into 2 functions:
launchProcess and injectDll.

With the new injection code I dont understand why it would be necessary to make it all ASYNC as this is a single shoot type of inejction, there is no state machine like in the current injection code.

Basically we create the process suspended, manipulate it's memory and that's it, so I'm not sure why ASYNC is required.

As for splitting into 2 functions like currently, that should be fairly simple to split (I dont know JS / Neon so I hope perhaps someone else can help with that part of the integration).

About bullet 3, as far as I can tell I do propagate the error all the way to the top (it's an anyhow, did you guys mean to have your own Err enum?)

@tec27 @2Pacalypse-, will appreciate your thoughts :)

**Comment by arilou** [comment]
Just adding here as a reference the current interface to JS:
https://github.com/ShieldBattery/ShieldBattery/blob/master/app/game/native/process/index.js

**Comment by 2Pacalypse-** [comment]
I can't really speak for other things, but Neon has decent documentation and doesn't look that particular hard to use: 
https://neon-bindings.com/docs/introduction

They even have some very useful examples that show how to use it (note `async-sqlite` and `tokio-fetch` examples in particular): 
https://github.com/neon-bindings/examples/tree/main/examples
